# Generated by Django 4.1.2 on 2022-10-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("height", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "garbage_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=5, null=True
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Garbage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("garbage_level", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "bin_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.bin"
                    ),
                ),
            ],
        ),
    ]
