# Generated by Django 4.1.4 on 2022-12-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_garbage_garbage_percentage_alter_bin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='moisture_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='garbage',
            name='moisture_status',
            field=models.BooleanField(default=False),
        ),
    ]
